version: "3"
services: 
  react-quiz:
    # stdin_open: true
    # tty: true
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"
    # volumes:
    #   - ./src:/app/src
    # environment:
    #   - REACT_APP_NAME =ashik
    env_file:
    - ./.env

